### ISSUE TITLE
 Different totals from the order to the invoice

### ISSUE THREAD

**Issue by halflores** [bgmulinari/B1SLayer#67] opened 2024-04-10 17:18 UTC
Hi, 
@bgmulinari
Why do I get different totals from the order to the invoice?
My input:
![image](https://github.com/bgmulinari/B1SLayer/assets/25017591/d9f572fd-1fd0-4a08-bb08-05248ae05b39)

                #region CREAR OFERTA DE VENTA, modelo a tomar
                var ofertaVenta = new
                {
                    CardCode = oferta.CardCode,
                    DocDueDate = oferta.DocDueDate,
                    DocumentLines = oferta.DocumentLines
                                     .Select(x => new
                                     {
                                         ItemCode = x.ItemCode,
                                         Quantity = x.Quantity,
                                         WarehouseCode = x.WhsCode,
                                         LineNum = x.LineNum,
                                         UoMEntry = x.UoMEntry
                                     }).ToList()
                };

                var objQuotations = new SLBatchRequest(
                    HttpMethod.Post,
                    "Quotations",
                    ofertaVenta,
                    1); // Content-ID for this entity
                #endregion

                #region CREAR ORDER VENTA, modelo a tomar
                var orderVenta = new
                {
                    CardCode = order.CardCode,
                    DocDueDate = order.DocDueDate,
                    PaymentGroupCode = order.PaymentGroupCode,
                    DocumentLines = order.DocumentLines
                                     .Select(x => new
                                     {
                                         BaseEntry = x.BaseEntry,
                                         BaseLine = x.BaseLine,
                                         BaseType = x.BaseType,
                                         WarehouseCode = x.WhsCode
                                     }).ToList()
                };

                var objOrders = new SLBatchRequest(
                    HttpMethod.Post,
                    "Orders",
                    orderVenta,
                    2);
                #endregion

                #region CREAR FACTURA VENTA, modelo a tomar
                var invoiceVenta = new
                {
                    CardCode = invoice.CardCode,
                    DocDueDate = invoice.DocDueDate,
                    PaymentGroupCode = invoice.PaymentGroupCode,
                    Indicator = 4,
                    Series = 142,
                    ReserveInvoice = "tYES",
                    DocType = "dDocument_Items",
                    DocumentLines = invoice.DocumentLines
                                     .Select(x => new
                                     {
                                         BaseEntry = x.BaseEntry,
                                         BaseLine = x.BaseLine,
                                         BaseType = x.BaseType,
                                         TaxCode = x.TaxCode,
                                         WarehouseCode = x.WhsCode
                                     }).ToList()
                };

                var objInvoice = new SLBatchRequest(
                    HttpMethod.Post,
                    "Invoices",
                    invoiceVenta,
                    3);
                #endregion

                Tuple<HttpResponseMessage[], string> results = await _slConnections[login.SLConexion].PostBatchAsync(objQuotations, objOrders, objInvoice);
![image](https://github.com/bgmulinari/B1SLayer/assets/25017591/a9562966-1e42-4736-a3b0-86fa7cf6edc7)

**Comment by bgmulinari** [comment] 2024-04-10 18:58
Hi, @halflores.

It's hard to know the cause of your issue without comparing the created documents in detail. 

In any case, I don't believe this issue is related to B1SLayer. Try reproducing the issue by sending the requests through Postman.

**Comment by bgmulinari** [comment] 2024-04-26 13:38
Hi, @halflores.

The relation between documents is defined in the document lines by the fields _BaseType_, _BaseEntry_ and _BaseLine_.

**Comment by halflores** [comment] 2024-04-26 13:49
Hi @bgmulinari 
It is absolutely understandable, as you can see in the first image. But when I use this way it recalculates the amount per line. Do you know how I can prevent it from being recalculated and keep it as if it were an individual document?

**Comment by bgmulinari** [comment] 2024-12-02 20:38
@halflores, I'm closing this issue. Let me know if you still need assistance.

**Closed by bgmulinari** 2024-12-02 20:38 UTC
